services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: BookRentalSystemDB
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: book-rental-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BookRentalSystemDB
      SPRING_DATASOURCE_USERNAME: secret
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: false
    #      SPRING_SQL_INIT_SCHEMA_LOCATIONS: file:./docker/init/01-schema.sql
    #      SPRING_SQL_INIT_DATA_LOCATIONS: file:./docker/init/02-data.sql
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: book-rental-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://backend:8080/api
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
