services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: BookRentalSystemDB
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: book-rental-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/BookRentalSystemDB
      SPRING_DATASOURCE_USERNAME: secret
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
